config/routes.rb
Rails.application.routes.draw do
  %i[https smtp xmpp tls ssh].each do |type|
    namespace type, id: /[^\/]+/ do
      get '/', action: :index
      get ':id/', action: :show, as: :show
      get ':id/refresh', action: :refresh, as: :refresh
    end
  end

  get 'help' => 'site#help'
  get 'about' => 'site#about'
  get 'ciphers' => 'site#ciphers'
  get 'suite' => 'site#suite_index'
  get 'suite/:id' => 'site#suite'
  post 'suite' => 'site#suite'
  root 'site#index'
  post '/' => 'site#check'

  get 'sites' => 'site#sites'

  %i[banks insurances gouv.fr].each do |name|
    get name, controller: :sites, action: name
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/site_controller.rb
require 'simpleidn'

class SiteController < ApplicationController
	def check
		host, port, type = params[:host], params[:port], params[:type]

		host = SimpleIDN.to_ascii host.downcase
		if host.blank? or /[^a-zA-Z0-9.-]/ =~ host
			flash[:danger] = "Hôte #{host} invalide"
			render :index
			return
		end

		unless port.blank?
			port = port.to_i
			unless (1..65535).include? port
				flash[:danger] = "Port #{port} invalide"
				render :index
				return
			end
			host = "#{host}:#{port}"
		end

		unless %w(https smtp xmpp tls ssh).include? type
			flash[:danger] = "Type #{type} invalide"
			render :index
			return
		end

		redirect_to "/#{type}/#{host}"
	end

	def suite
		@suite = params[:id] || params.require(:suite)
		@ciphers = CryptCheck::Tls::Cipher.list @suite
	end

	def help
	end

	def about

	end

	def sites
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  @@sites = YAML.load_file Rails.root.join 'config/sites.yml'
  @@sites.keys.each do |name|
    define_method(name) { sites name }
  end

  private

  def sites(name)
    @name = name
    @sites = Stat[:"sites_#{name}"].data
    render :sites
  end
end

app/helpers/site_helper.rb
module SiteHelper
	include CheckHelper

	def rfc_link_to(rfc)
		link_to "RFC #{rfc}", "https://tools.ietf.org/html/rfc#{rfc}", target: :_blank
	end

	def wikipedia_link_to(content, page)
		link_to content, "https://en.wikipedia.org/wiki/#{page}", target: :_blank
	end
end

app/helpers/sites_helper.rb
module SitesHelper
  include CheckHelper

  def domain_cell(domain, grade)
    link = link_to domain, https_show_path(domain)
    content_tag :th, (rank_label(grade) + ' ' + link).html_safe
  end

  def tls_cell(tls)
    return unless tls
    color   = case tls.to_sym
              when :tls1_2_only
                :success
              when :tls1_2
                :error
              else
                :critical
              end
    content = content_tag :div, color, class: %i[sr-only]
    content_tag :td, label(' ' + content, color), class: %i[text-center]
  end

  def ciphers_cell(ciphers)
    return unless ciphers
    color   = case ciphers.to_sym
              when :good
                :success
              else
                :critical
              end
    content = content_tag :div, color, class: %i[sr-only]
    content_tag :td, label(' ' + content, color), class: %i[text-center]
  end

  def pfs_cell(pfs)
    return unless pfs
    color   = case pfs.to_sym
              when :pfs_only
                :success
              when :pfs
                :error
              else
                :critical
              end
    content = content_tag :div, color, class: %i[sr-only]
    content_tag :td, label(' ' + content, color), class: %i[text-center]
  end
end

app/views/site/_checks.html.erb
<h1>Checks</h1>
<h2>Protection</h2>
<h3>Hard protection</h3>

<p>
	Such protection are hard or risky to deploy but give strong protection
	against attack.<br/>
	Deploying such protection can just break your service for a long time if you
	don't understand what you are doing.<br/>
	Service using such protection really tries to protect you and really know
	what security is.
</p>
<hr/>

<h4 id="hpkp">
	<%= rank_label :A %>
	HTTP Public Key Pinning (HPKP)
	<span class="small">HTTPS only, incoming feature</span>
</h4>

<p>
	HPKP protection, specified in <%= rfc_link_to 7469 %>, consists of putting
	headers on HTTP response to specify which keys or certificats are allowe
	for the encryption.
	If pinning mismatches, for example because of a
	<%= wikipedia_link_to 'man-in-the-middle attack', 'Man-in-the-middle_attack' %>
	connection is rejected and no data at all is transfered.
</p>

<pre>
	<code>
$ curl -sI https://cryptcheck.fr/ | grep public-key-pins
public-key-pins: report-uri="https://aeris.report-uri.io/r/default/hpkp/enforce"; max-age=5184000;
		pin-sha256="wdkD38iQQzxE7g0RpmN8VoaIqX7YmPWwoueD9Iqawfg="; pin-sha256="EswdUzfH2N8sx6Nb4Vr9gamtNF5VWQxLWUG0gDIPVLw=";
	</code>
</pre>

<p>
	HPKP is difficult to deploy because has a redemption period of some days
	(maximum allowed: 60). During this time, in case of misconfiguration,
	returning visitors will faced a TLS error page, even if the configuration
	was fixed.
</p>

<hr/>

<h3>Medium protection</h3>

<p>
	Such protection is not so easy to deploy and can have hazardous side effects,
	but provides quiet good protection against some attacks.<br/>
	Broken service is unexpected or could be fixed in a small time range.<br/>
	Using such protection is a clear sign the service try to protect you.
</p>

<hr/>

<h4 id="hsts">
	<%= rank_label :A %>&nbsp;<%= rank_label :B %>
	HTTP Strict Transport Security (HSTS)
	<span class="small">HTTPS only</span>
</h4>

<p>
	HSTS protection, specified in <%= rfc_link_to 6797 %>, consists of putting
	headers on HTTP response to specify the service supports HTTPS.<br/>
	After the first connection (HSTS is
	"<%= wikipedia_link_to 'Trust On First Use', 'Trust_on_first_use' %>" (TOFU)),
	the browser automatically rewrite <code>http://</code> address to
	<code>https://</code>, avoiding a plain request (with potential data leak)
	to be asked by the service to redirect to the <code>https://</code> address.
</p>

<pre>
	<code>
curl -sI https://cryptcheck.fr/ | grep strict-transport-security
strict-transport-security: max-age=31536000; includeSubDomains; preload;
	</code>
</pre>

<p>
	To have full score on HSTS, you need to have a long <code>max-age</code>
	period, at least 1 year (<code>31536000</code> seconds).<br/>
	If you correctly configure your service with HSTS, you can also ask for
	<a href="https://hstspreload.org/" target="_blank">browser preloading</a>,
	avoiding the trouble of the first connection.
</p>

<hr/>

<h3>Easy protection</h3>

<p>
	Such protection is easy to deploy and without .<br/>
	Broken service is unexpected or could be fixed in a small time range.<br/>
	Using such protection is a clear sign the service try to protect you.
</p>

<hr/>

<h4 id="aead">
	<%= rank_label :C %>
	Authentificated Encryption with Authenticated Data (AEAD)
</h4>

<p>
	Since 2014, TLS (and SSL) suffers of
	<a href="https://www.imperialviolet.org/2014/12/08/poodleagain.html" target="_blank">PODDLE</a>
	vulnerability on the way padding is done during TLS handshake.
	An attacker can play with this encrypted padding to guess underlying plain
	data.<br/>

	Any <%= wikipedia_link_to 'cipher mode operation', 'Block_cipher_mode_of_operation' %>
	other than <%= wikipedia_link_to 'AEAD', 'Authenticated_encryption' %> is
	vulnerable to this attack.
</p>

<p>
	In practice, POODLE is a serious flaw for SSLv2/v3, which must be avoided
	in all cases, but also for TLSv1.0/1.1.<br/>
	Service operators must support AEAD cipher suite as soon as possible, to
	avoid trouble when practical attack will be found on POODLE on TLS.<br/>
	Such cipher suite is only available on TLSv1.2, so operators must disable
	TLSv1.0 now, and TLSv1.1 as soon as possible.
</p>

<hr/>

<h4 id="scsv">
	<%= rank_label :C %>
	TLS Fallback Signaling Cipher Suite Value (SCSV)
</h4>

<p>
	SCSV, specify in <%= rfc_link_to 7507 %> is a TLS extension to allow a
	client to signal to the server a previous hanshake attempt with higher TLS
	version was done, but unsuccessfully.<br/>
	This way, the server can detect a downgrade attack on the line, because
	supporting better than the current TLS version.<br/>
	Without this signaling value, the server has no way to distinguish between
	a client supporting TLSv1.2 but downgraded to TLSv1.1 and a client TLSv1.1
	only.<br/>
	For example, this feature allows blocking of downgrade attack from TLSv1.2
	(AEAD & PFS) to TLSv1.0 (nor AEAD nor PFS) to exploit POODLE vulnerability
	more easily.
</p>

<p>
	To activate SCSV, you just need a decent OpenSSL version (1.0.1j+).
	LibreSSL currently doesn't have support for this.
</p>

<hr/>

<h2>Weaknesses</h2>
<h3>Future weakness</h3>

<p>
	This kind of weakness is theorical vulnerability but without practical
	attack or with too much side effects to be able to patch it.
</p>

<hr/>

<h3>Current weakness</h3>

<p>
	Such weakness knows practical attacks to break encryption.
	Using such features is hightly discourage, and operators must take quick
	actions to remove them.
</p>

<hr/>

<h4 id="tlsv1.0">
	<%= rank_label :F %>
	TLSv1.0
</h4>

<p>
	TLSv1.0 is vulnerable to
</p>

<hr/>

<!--
<h4 id="pfs">
	<%= rank_label :F %>
	Perfect Forward Secrecy (PFS)
</h4>

<p>
	<%= wikipedia_link_to 'PFS', 'Forward_secrecy' %> is
</p>

<hr/>
-->

<h3>Deprecated feature</h3>

<hr/>

<h4 id="ssl">
	<%= rank_label :G %>
	SSLv2, SSLv3
</h4>

<p>
	SSLv2 and SSLv3 are deprecated SSL protocol version.<br/>
	Pratical attacks exist to decrypt SSL encrypted traffic to plain text in
	some minutes with standard computer.
	For SSLv3, it's
	<a href="https://security.googleblog.com/2014/10/this-poodle-bites-exploiting-ssl-30.html" target="_blank">POODLE</a>
	again.
	For SSLv2, it's was supposed to never be in production because too bad and
	broken cryptography under the hood.
	<a href="https://drownattack.com/" target="_blank">DROWN</a> vulnerability
	allows an attacker to decrypt encrypted traffic (even TLSv1.2!) as soon as
	one of the servers used for the service supports SSLv2 with the same key.
</p>

<hr/>

<!--
<h4 id="rc4">
	<%= rank_label :G %>
	RC4
</h4>

<p>
	<%= wikipedia_link_to 'RC4', 'RC4' %> is a stream cipher, recently known to
	have
</p>

<hr/>
-->

<h4 id="sha1">
	<%= rank_label :E %>&nbsp;<%= rank_label :G %>
	SHA-1
	<span class="small">incoming feature for HMAC</span>
</h4>

<p>
	<%= wikipedia_link_to 'SHA-1', 'SHA-1' %> is a cryptographic hash function
	used in TLS cipher suite.
	<a href="https://shattered.io/" target="_blank">It was broken</a> in 2016.
</p>

<p>
	SHA-1 is used in two parts of the handshake.<br/>
	For <%= wikipedia_link_to 'HMAC', 'Hash-based_message_authentication_code' %>,
	which protect each messages exchanged during handshake. Because lifetime of
	such HMAC is very short (TCP/IP round trip), SHA-1 collision is not a real
	trouble on this part.<br/>
	For key exchange and authentication. Each certificate is signed by the issuer
	certificate using a digest.
	In this case, if SHA-1 digest is used and because certificate lifetime is
	long (years to decades), collision on digest could allow an attacker to
	forge a rogue certificate which match the real certificate digest, and so
	to impersonate the TLS service behind.
</p>

<p>
	SHA-1 signed certificates must be banned.<br/>
	SHA-1 HMAC is currently quite safe, but operators must take action to ensure
	SHA-2 compatibility with clients in case if SHA-1 must be revoked even for
	HMAC.
</p>

<hr/>

<h4 id="digest">
	<%= rank_label :G %>
	MD-5, MD-4, MD-2, MDC-2
</h4>

<p>
	MD-5, MD-4, MD-2 and MDC-2 are completely broken hash function.
	Just don't use it.
</p>

<h4 id="compression">
	<%= rank_label :G %>
	Compression
	<span class="small">incoming feature</span>
</h4>

<p>
	With TLS compression activated, some oracle attacks allow to decrypt the
	content.
	For example the
	<a href="https://arstechnica.com/information-technology/2013/08/gone-in-30-seconds-new-attack-plucks-secrets-from-https-protected-pages/" target="_blank">BREACH</a>
	or
	<a href="https://threatpost.com/crime-attack-uses-compression-ratio-tls-requests-side-channel-hijack-secure-sessions-091312/77006/" target="_blank">CRIME</a>
	attacks.
</p>

<p>
	TLS compression must be disabled on the service.
</p>

app/views/site/_scoring.html.erb
<h1>Scoring</h1>

<p>
	Currently, CryptCheck gives note from <%= rank_label :G %> for the
	worst sites to <%= rank_label :'A+' %> for the best ones.
</p>

<p>
	Scoring is based on the fact that TLS handshake is <b>not</b> authenticated,
	and so an attacker can force to use whatever cipher he wants as soon as both
	client and server support it, with a downgrade attack as simple as modify
	TCP packets on the fly.
</p>

<p>
	Such downgrade attack doesn't require heavy resources and can be made with
	standard computer or phone.<br/>
	The only difficult part is to be in position to modify the traffic between
	the client and the server.
	This is the case if the attacker is connected on the same network as the
	client (hotspot, 3G…) with simple
	<%= wikipedia_link_to 'ARP spoofing', 'ARP_spoofing' %>, doable with tools
	like
	<a href="https://forum.xda-developers.com/showthread.php?t=1593990">Droid Sheep</a>.<br/>
</p>

<p>
	As client support can't be guessed, CryptCheck considers the <b>weakest</b>
	suite supported server side.
	This way, a connection to the scored service can't lead to a negociated
	handshake with a worse score than the one given to the service, whatever
	your client supports and whatever an attacker is present or not.
</p>

<table class="scoring table table-bordered table-condensed center table-striped">
	<thead>
	<tr>
		<th rowspan="2">Score</th>
		<td rowspan="2"></td>
		<th colspan="3">Protection</th>
		<th colspan="3">Weakness</th>
	</tr>
	<tr>
		<th>Hard</th>
		<th>Medium</th>
		<th>Easy</th>

		<th>Future</th>
		<th>Weak</th>
		<th>Deprecated</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><%= rank_label :'A+' %></td>
		<td class="left">
			Seriously take security into account and invest a lot on it.<br/>
			Whatever the cost, encryption safety is implemented.
			You can be proud!
		</td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :A %></td>
		<td class="left">
			Seriously take security into account and invest a lot on it.
		</td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :'B+' %></td>
		<td class="left">
			Seriously take security into account and invest on it.
		</td>
		<td></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :B %></td>
		<td class="left">
			Take security into account and invest on it.
		</td>
		<td></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :'C+' %></td>
		<td class="left">
			Take security into account and invest a little on it.
		</td>
		<td></td>
		<td></td>
		<td><%= image_tag 'check-full.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :C %></td>
		<td class="left">
			Take security into account but don't spend too much for it.
		</td>
		<td></td>
		<td></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :D %></td>
		<td class="left">
			Take security into account. Minimaly.<br/>
			This is the worst score a decent service must have today.
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :E %></td>
		<td class="left">
			Take security into account. A little. Or not.
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td><%= image_tag 'cross-red.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :F %></td>
		<td class="left">
			Just don't take security into account.
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td><%= image_tag 'cross-red.svg' %></td>
		<td><%= image_tag 'check-empty.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :G %></td>
		<td class="left">
			Just don't take security into account at all.<br/>
			What the fuck you do, dude?
		</td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td><%= image_tag 'cross-red.svg' %></td>
	</tr>
	<tr>
		<td><%= rank_label :'0' %></td>
		<td class="left">
			No security at all. Just plain text.<br/>
			Seriously, in <%= Date.today.year %>?
		</td>
		<td colspan="6"></td>
	</tr>
	<tr>
		<td><%= rank_label :V %></td>
		<td class="left">
			Invalid certificate (wrong domain, expired…)
		</td>
		<td colspan="6"></td>
	</tr>
	<tr>
		<td><%= rank_label :T %></td>
		<td class="left">
			Unstrusted certificate. Not issued by a trusted
			<a href="https://ccadb-public.secure.force.com/mozilla/IncludedCACertificateReport">certificate authority</a>.
		</td>
		<td colspan="6"></td>
	</tr>
	<tr>
		<td><%= rank_label :X %></td>
		<td class="left">
			Error occurs during the analysis. Try again later?
		</td>
		<td colspan="6"></td>
	</tr>
	</tbody>
</table>
<table class="scoring table table-bordered table-condensed">
	<tr>
		<td>
			For protection:<br/>
			<%= image_tag 'check-full.svg' %> Fully implemented
			<%= image_tag 'check-empty.svg' %> Partially implemented<br/>

			Easy: simple to implement, small protection<br/>
			Medium: quiet hard to implement, middle protection<br/>
			Hard: hard to implement, strong protection
		</td>
		<td>
			For weakness:<br/>
			<%= image_tag 'check-empty.svg' %> Not vulnerable
			<%= image_tag 'cross-red.svg' %> Vulnerable<br/>

			Future: known weakness, but no practical attack known<br/>
			Weak: known weakness, pratical attack exist<br/>
			Deprecated: known weakness, merely equivalent or equal to plain text
		</td>
	</tr>
</table>

<p>
	<i>Note</i>: Unlike HTTPS or XMPP, SMTP uses
	<%= wikipedia_link_to 'opportunistic encryption', 'Opportunistic_TLS' %>.<br/>
	When you send an email, the server used to forward the mail (the
	<%= wikipedia_link_to 'MTA', 'Message_transfer_agent' %> to the recipient
	has no way to guess in advance if recipient MTA supports or not encryption
	and which cipher suite will be available.
	To avoid your email returning to you in case of failure, the standard for
	email encryption (<%= rfc_link_to 3207 %>) requires to retry
	<b>in plain text</b> in case of encryption handshake failure.<br/>
	So, for SMTP, there is a compromise to make between strong configuration,
	leading to plain text fallback for old or badly configured MTA, and
	compatibility with such MTA to use weak encryption better than plain text
	but allowing downgrade attack on stronger MTA.<br/>
	Given email is a real nightmare for security, with multiple way to force a
	connection to fallback to plain text
	(<a href="https://www.eff.org/fr/deeplinks/2014/11/starttls-downgrade-attacks">STARTTLS stripping</a>,
	<a href="https://labs.ripe.net/Members/stephane_bortzmeyer/dns-censorship-dns-lies-seen-by-atlas-probes">MX lying</a>…),
	CryptCheck scores SMTP as HTTPS or XMPP and doesn't care about compatibility
	trouble. This way, weak people are still weak, but strong people can (not
	too much) hope strong encryption under normal condition.<br/>
	Be advice than strong score here for SMTP means compatibility troubles.
	Or fucked service which doesn't take care of your security.
	I don't know, you turn to judge.
</p>

app/views/site/help.html.erb
<div id="help" class="container">
	<div class="scoring row">
		<div class="col-sm-12">
			<%= render partial: 'scoring' %>
		</div>
	</div>
	<div class="checks row">
		<div class="col-sm-12">
			<%= render partial: 'checks' %>
		</div>
	</div>
</div>

app/views/site/index.html.erb
<h1><%= t 'Check your domain' %></h1>
<%= form_tag root_path, class: %i[container-fluid] do %>
	<div class="row input-group input-group-lg mb-3">
		<div class="col input-group-lg">
			<%= text_field_tag :host, nil, class: %i[form-control],
							   placeholder:       'your-site.com', required: true %>
		</div>

		<div class="col-auto input-group-lg">
			<%= select_tag :type, options_for_select({ 'HTTPS' => :https, 'SMTP' => :smtp, 'XMPP' => :xmpp }), class: %i[form-select] %>
		</div>

		<div class="col-auto input-group-lg">
			<%= submit_tag t('Test me!'), class: %i[btn btn-outline-dark] %>
		</div>
	</div>
<% end %>

app/views/site/result.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-11">
			<h1>
				Résultats pour <%= @host %> <span class="small">(<%= l @result.date %>)</span>
				<%= rank_label @result.score.rank %>
			</h1>
		</div>
		<% if Time.now - @result.date >= Rails.configuration.refresh_delay %>
		<div class="col-sm-1">
			<%= link_to 'Rafraîchir', refresh_path, class: %i(btn btn-default) %>
		</div>
		<% end %>
	</div>
	<br/>
	<div class="row">
		<div class="col-sm-6">
			<% scores = @result.score.details %>
			<table class="table table-bordered table-condensed table-striped">
				<thead>
					<tr>
						<th colspan="2">
							Scores
							<%= rank_label @result.score.rank %>
						</th>
					</tr>
				</thead>
				<tbody>
					<%
					   { 'Protocole' => 'protocol',
						 'Échange de clef' => 'key_exchange',
						 'Chiffrement' => 'cipher_strengths',
						 'Total' => 'score'}.each do |name, v| %>
					<tr>
						<th class="col-sm-4"><%= name %></th>
						<td class="col-sm-8"><%= score_progress scores[v] %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="col-sm-6">
			<table class="table table-bordered table-condensed table-striped">
				<tbody>
					<tr>
						<th class="col-sm-4">Protocoles</th>
						<td class="col-sm-8"><%= protocol_labels @result.protocols %></td>
					</tr>
					<tr>
						<th>Clefs</th>
						<td>
							<p>Certificat : <%= key_label @result[:key] %></p>
							<p>Diffie Hellman : <%= key_labels @result.dh %></p>
						</td>
					</tr>
					<% { 'Bonnes pratiques' => ['success', 'success'],
					 'Alertes' => ['warning', 'warning'],
					 'Erreurs' => ['error', 'danger'] }.each do |name, v| %>
					<tr>
						<th><%= name %></th>
						<td>
							<% item, color = v
							(@result.score[item] || []).each do |item| %>
							<span class="label label-<%= color %>"><%= item.upcase %></span>
							<% end %>
						</td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered table-condensed table-striped">
				<thead>
					<tr>
						<th class="col-sm-3">Algorithme</th>
						<th class="col-sm-1">Clef</th>
						<th class="col-sm-1">DH</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% %w(TLSv1_2 TLSv1_1 TLSv1 SSLv3 SSLv2).each do |protocol|
						ciphers = @result.ciphers.select { |c| c.protocol == protocol }
								.sort { |a, b| -1 * (a['size'] <=> b['size']) }
						unless ciphers.empty? %>
					<tr>
						<th colspan="3"><%= protocol_label protocol %></th>
					</tr>
							<% ciphers.each do |cipher| %>
					<tr>
						<td><%= cipher.name %></td>
						<td><%= cipher_label cipher %></td>
						<td><%= key_label cipher.dh if cipher.dh %></td>
						<td><%= cipher_labels cipher %></td>
					</tr>
					<% 	end end end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/site/suite_index.html.erb
<h1><%= t 'User agent compatibility' %></h1>
<h2><%= t 'Cipher suite' %></h2>
<%= form_tag suite_path, class: %i[container-fluid] do %>
	<div class="row input-group input-group-lg mb-3">
		<div class="col input-group-lg">
			<%= text_field_tag :suite, nil, class: %i[form-control], placeholder: 'EECDH+AES' %>
		</div>

		<div class="col-auto input-group-lg">
			<%= submit_tag t('Test me!'), class: %i[btn btn-outline-dark] %>
		</div>
	</div>
<% end %>
</div>