config/routes.rb
Rails.application.routes.draw do
  %i[https smtp xmpp tls ssh].each do |type|
    namespace type, id: /[^\/]+/ do
      get '/', action: :index
      get ':id/', action: :show, as: :show
      get ':id/refresh', action: :refresh, as: :refresh
    end
  end

  get 'help' => 'site#help'
  get 'about' => 'site#about'
  get 'ciphers' => 'site#ciphers'
  get 'suite' => 'site#suite_index'
  get 'suite/:id' => 'site#suite'
  post 'suite' => 'site#suite'
  root 'site#index'
  post '/' => 'site#check'

  get 'sites' => 'site#sites'

  %i[banks insurances gouv.fr].each do |name|
    get name, controller: :sites, action: name
  end

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	include HttpAcceptLanguage::AutoLocale
end

app/views/application/_flash.erb
<div id="flash" class="container">
	<% [:danger, :warning, :success, :info].each do |level|
		message = flash[level]
		unless message.nil? %>
			<%= content_tag :div, class: %(alert alert-#{level}) do %>
				<% if message.is_a? Enumerable %>
					<ul>
						<% message.each do |m| %>
							<li><%= m %></li>
						<% end %>
					</ul>
				<% else %>
					<%= message %>
				<% end %>
			<% end
			   end
			   end %>
</div>

app/views/application/_headers.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
	<div class="container-fluid">
		<%= link_to 'CryptCheck', root_path, class: %i(navbar-brand) %>

		<ul class="navbar-nav mr-auto me-auto mb-2 mb-lg-0">
			<li class="nav-item"><%= link_to 'HTTPS / SMTP / XMPP', root_path, class: %i(nav-link) %></li>
			<li class="nav-item"><%= link_to 'TLS', tls_path, class: %i(nav-link) %></li>
			<li class="nav-item"><%= link_to 'SSH', ssh_path, class: %i(nav-link) %></li>
		</ul>

		<ul class="navbar-nav mr-auto ms-auto mb-2 mb-lg-0">
			<li class="nav-item"><%= link_to t('User agent compatibility'), suite_path, class: %i(nav-link) %></li>
			<li class="nav-item"><%= link_to t('Supported cipher suites'), ciphers_path, class: %i(nav-link) %></li>
			<li class="nav-item"><%= link_to t('Help'), help_path, class: %i(nav-link) %></li>
			<li class="nav-item"><%= link_to t('About'), about_path, class: %i(nav-link) %></li>
		</ul>
	</div>
</nav>

app/views/application/sites.html.erb
<h1><%= @name.to_s.capitalize %></h1>

<h2>Columns meaning</h2>

<div class="container">
	<div class="form-group row">
		<div class="col-sm-1">TLS:</div>
		<div class="col-sm-11">
			<%= label(' ' + content_tag(:span, :success, class: %i[sr-only]), :success) %> TLS1.2 only supported
			<%= label(' ' + content_tag(:span, :error, class: %i[sr-only]), :error) %> No TLS1.2 supported
			<%= label(' ' + content_tag(:span, :critical, class: %i[sr-only]), :critical) %> SSLv2 or SSLv3 supported
		</div>
	</div>
	<div class="row">
		<div class="col-sm-1">Ciphers:</div>
		<div class="col-sm-11">
			<%= label(' ' + content_tag(:span, :success, class: %i[sr-only]), :success) %> Only safe cipher supported
			<%= label(' ' + content_tag(:span, :critical, class: %i[sr-only]), :critical) %> Unsafe cipher supported
		</div>
	</div>
	<div class="row">
		<div class="col-sm-1">PFS:</div>
		<div class="col-sm-11">
			<%= label(' ' + content_tag(:span, :success, class: %i[sr-only]), :success) %> Only PFS cipher supported
			<%= label(' ' + content_tag(:span, :error, class: %i[sr-only]), :error) %> PFS cipher but also no-PFS cipher supported
			<%= label(' ' + content_tag(:span, :critical, class: %i[sr-only]), :critical) %> No PFS supported
		</div>
	</div>
<br/>

<table class="table table-sm">
	<thead>
	<tr>
		<%= content_tag :th, t('.domain') %>
		<%= content_tag :th, t('.tls'), class: %i[text-center] %>
		<%= content_tag :th, t('.ciphers'), class: %i[text-center] %>
		<%= content_tag :th, t('.pfs'), class: %i[text-center] %>
	</tr>
	</thead>
	<tbody>
	<% @sites.sort_by { _2.fetch('grade') || 'Z' }.each do |domain, stat| %>
		<tr>
			<%= domain_cell domain, stat.fetch('grade') %>
			<%= tls_cell stat.fetch 'tls' %>
			<%= ciphers_cell stat.fetch 'ciphers' %>
			<%= pfs_cell stat.fetch 'pfs' %>
		</tr>
	<% end %>
	</tbody>
</table>